### ISSUE TITLE
custom arrow icons and dots below

### ISSUE THREAD

**Issue by salicius** [YourSurpriseCom/slider#14]
is it possible change icons ? and put dots below slider ?

**Comment by iFiz** [comment]
It's currently not possible to change the icons. In the future we'd like to make it possible to pass custom buttons to the Slider, which will allow you to use your own icons (and styling). But I don't have any ETA on this. If you're up for it, you could create a merge request for this. 

Dots below the slider is currently not in the works, the idea is to keep the slider as basic as possible. But you could create a custom implementation with the provided events, as shown here: https://github.com/YourSurpriseCom/slider#example-on-how-to-access-the-slider-api.
